/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "gjcqmjmialtvsiomrfmo"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqY3Ftam1pYWx0dnNpb21yZm1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODIyNzE1OTQsImV4cCI6MjA5Nzg0NzU5NH0.jd2sYo-EWbR3-2OAOy4u8E7jYMVlCoo9KKDwUFcIHyc"